/**
 * Markdown Export Utilities
 *
 * Converts Specification objects to Markdown format for repo commit.
 * Follows the template defined in PRD F4 requirements.
 */

import type { Specification, Requirement } from './schemas';

/**
 * Generates Markdown content from a Specification
 *
 * @param spec - The specification to export
 * @param includeMetadata - Whether to include metadata section (default: false)
 * @returns Markdown-formatted string ready for download/commit
 *
 * @example
 * ```typescript
 * const markdown = generateMarkdown(spec);
 * // Returns:
 * // # User Authentication Flow
 * //
 * // ## Overview
 * // Implement SSO login with Google and Microsoft
 * // ...
 * ```
 */
export function generateMarkdown(
  spec: Specification,
  includeMetadata = false
): string {
  const sections: string[] = [];

  // Title
  sections.push(`# ${spec.title}\n`);

  // Overview
  sections.push(`## Overview\n`);
  sections.push(`${spec.description}\n`);

  // Requirements
  if (spec.requirements.length > 0) {
    sections.push(`## Requirements\n`);

    // Group requirements by category
    const grouped = groupRequirementsByCategory(spec.requirements);

    for (const [category, reqs] of Object.entries(grouped)) {
      if (reqs.length > 0) {
        sections.push(`### ${formatCategoryName(category)}\n`);
        reqs.forEach((req, index) => {
          const priority = formatPriority(req.priority);
          sections.push(`${index + 1}. **[${priority}]** ${req.text}\n`);
        });
        sections.push('');
      }
    }
  }

  // Acceptance Tests
  if (spec.acceptanceTests.length > 0) {
    sections.push(`## Acceptance Tests\n`);

    spec.acceptanceTests.forEach((test, index) => {
      sections.push(`### Test ${index + 1}: ${test.scenario}\n`);
      sections.push('```gherkin');
      sections.push(`Scenario: ${test.scenario}`);
      sections.push(`  Given ${test.given}`);
      sections.push(`  When ${test.when}`);
      sections.push(`  Then ${test.then}`);
      sections.push('```\n');
    });
  }

  // Metadata (optional)
  if (includeMetadata && spec.metadata) {
    sections.push(`## Metadata\n`);
    sections.push(`- **Dialogue Turns:** ${spec.metadata.dialogueTurnCount}`);

    if (spec.metadata.timeToCompleteSec !== undefined) {
      const minutes = Math.floor(spec.metadata.timeToCompleteSec / 60);
      sections.push(`- **Time to Complete:** ${minutes} minutes`);
    }

    if (spec.metadata.personasUsed.length > 0) {
      const personas = spec.metadata.personasUsed.map(formatPersonaName).join(', ');
      sections.push(`- **Personas Used:** ${personas}`);
    }

    if (spec.metadata.aiTokensUsed !== undefined) {
      sections.push(`- **AI Tokens Used:** ${spec.metadata.aiTokensUsed.toLocaleString()}`);
    }

    sections.push('');
  }

  // Links to external systems
  const hasLinks = spec.linkedGithubPR || spec.linkedLinearIssue || spec.linkedJiraIssue;
  if (hasLinks) {
    sections.push(`## Related Links\n`);

    if (spec.linkedGithubPR) {
      sections.push(`- [GitHub PR](${spec.linkedGithubPR})`);
    }
    if (spec.linkedLinearIssue) {
      sections.push(`- [Linear Issue](${spec.linkedLinearIssue})`);
    }
    if (spec.linkedJiraIssue) {
      sections.push(`- [Jira Issue](${spec.linkedJiraIssue})`);
    }

    sections.push('');
  }

  // Footer
  sections.push('---\n');
  sections.push(`*Generated by Discovery Loop Coach on ${new Date().toISOString().split('T')[0]}*`);

  return sections.join('\n');
}

/**
 * Groups requirements by category for organized output
 */
function groupRequirementsByCategory(requirements: Requirement[]): Record<string, Requirement[]> {
  const grouped: Record<string, Requirement[]> = {
    functional: [],
    non_functional: [],
    security: [],
    performance: [],
    ux: [],
    business_rule: [],
  };

  requirements.forEach((req) => {
    if (grouped[req.category]) {
      grouped[req.category].push(req);
    }
  });

  return grouped;
}

/**
 * Formats category names for display
 */
function formatCategoryName(category: string): string {
  const names: Record<string, string> = {
    functional: 'Functional Requirements',
    non_functional: 'Non-Functional Requirements',
    security: 'Security Requirements',
    performance: 'Performance Requirements',
    ux: 'UX Requirements',
    business_rule: 'Business Rules',
  };

  return names[category] || category;
}

/**
 * Formats priority for display
 */
function formatPriority(priority: string): string {
  return priority.charAt(0).toUpperCase() + priority.slice(1);
}

/**
 * Formats persona type for display
 */
function formatPersonaName(persona: string): string {
  const names: Record<string, string> = {
    product_coach: 'Product Coach',
    security_expert: 'Security Expert',
    ux_analyst: 'UX Analyst',
    domain_expert: 'Domain Expert',
  };

  return names[persona] || persona;
}

/**
 * Generates a filename for the exported Markdown
 *
 * @param spec - The specification
 * @returns A safe filename with .md extension
 *
 * @example
 * ```typescript
 * generateFilename(spec)
 * // Returns: "user-authentication-flow.md"
 * ```
 */
export function generateFilename(spec: Specification): string {
  const slug = spec.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

  return `${slug}.md`;
}
